# Uncomment this line to define a global platform for your project
platform :ios, "8.0"
use_frameworks!

target 'HelloWorld' do

	pod 'SwiftyJSON', '~> 2.2.1'

	pod 'Alamofire', '~> 1.3'
    
    pod 'BrightFutures'

end

target 'HelloWorldTests' do

end

